from turtle import Turtle

arseniy = Turtle()
artem = Turtle()
arseniy.pencolor("red")
artem.pencolor("blue")

for _ in range(10):
    arseniy.left(90)
    artem.right(90)
    arseniy.forward(100)
    artem.forward(100)
    arseniy.left(90)
    artem.left(90)
    arseniy.forward(100)
    artem.forward(100)
    arseniy.left(90)
    artem.left(90)
    arseniy.forward(400)
    artem.forward(400)
    arseniy.left(90)
    arseniy.forward(100)
    artem.left(90)
    artem.forward(100)
    arseniy.left(90)
    artem.left(90)
    arseniy.forward(200)
    artem.forward(200)
    arseniy.right(90)
    artem.right(90)
    arseniy.forward(300)
    artem.forward(300)
    arseniy.right(90)
    artem.right(90)
    arseniy.forward(100)
    artem.forward(100)
    arseniy.right(90)
    artem.right(90)
    arseniy.forward(300)
    artem.forward(300)
    arseniy.reset()
    artem.reset()

s = arseniy.getscreen()
s.mainloop()